Minor docs changes
bellshade/Python pull request #151
Opened 2021-11-07 09:28 UTC by LuminetteBourgeons

# Deskripsi (Description)

memperbaiki kesalahan docs minor (kesalahan eja, typo, huruf kapital)

# Checklist:
##### Umum:
- [ ] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [x] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [ ] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [ ] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [ ] pytest
- [ ] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = `` windows ``
- ``python`` = ``python3 -V (unix) / py -3 -V (Windows-Python launcher)``

linked issue #NOMOR_ISSUE

2021-11-07 10:40 UTC, AdhyWiranto44 requested changes

2021-11-07 10:40 UTC, AdhyWiranto44 commented on Basic/README.md
> +2. [Variable dan data types ( primitive )](2_variable)
Ini kenapa ya digabung, bukannya keduanya ada direktori masing-masing?

2021-11-07 10:40 UTC, AdhyWiranto44 commented on Basic/README.md
> +5. [Input / output](5_input_output)
kenapa ya "o" di output dijadikan kecil? Berlaku juga untuk yang lain yang diubah dari huruf kapital menjadi huruf kecil.

2021-11-07 14:58 UTC, athallahmaajid approved these changes
udah bagus mbak, tinggal ikutin yang dibilang mas adhy aja

2021-11-08 01:05 UTC, LuminetteBourgeons commented on Basic/README.md
> +2. [Variable dan data types ( primitive )](2_variable)
maaf om saya ga teliti ini saya perbaiki

2021-11-08 03:17 UTC, slowy07 commented
amend commitnya ikutin dari ``CONTRIBUTING.md`` @LuminetteBourgeons

2021-11-10 18:17 UTC, merged