add:list and dictionary comprehension
bellshade/Python pull request #152
Opened 2021-11-07 14:49 UTC by KelvinMulyawan

# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [ ] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [ ] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [x] pytest
- [x] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``windows``
- ``python`` = ``py .3 .9```

linked issue #139

2021-11-08 02:34 UTC, athallahmaajid reviewed
bahasa indo aja bang

2021-11-08 03:19 UTC, slowy07 commented
filenya masukkan ke dalam folder ``basic``

2021-11-08 03:55 UTC, KelvinMulyawan commented
Overall selain bahasa dan folder gimana om @athallahmaajid sensei @slowy07 ??

2021-11-08 23:17 UTC, athallahmaajid commented
> Overall selain bahasa dan folder gimana om @athallahmaajid sensei @slowy07 ??

kayanya harus dijelasin dulu mau ngapain om, soalnya disitu cuma ada contoh dan tidak ada penjelasan apa gunanya dict comprehension

2021-11-11 13:12 UTC, athallahmaajid approved these changes

2021-11-12 08:17 UTC, slowy07 reviewed
tambahkan penjelasannya terlebih dahulu

2021-11-17 12:18 UTC, athallahmaajid approved these changes

2021-11-17 13:15 UTC, nomadkode approved these changes
Kalo dari aku sih udah mantap. LGTM 🚀

2021-11-24 01:58 UTC, AdhyWiranto44 requested changes

2021-11-24 01:58 UTC, AdhyWiranto44 commented on Basic/list_comprehension.py
> +print("Original Range : {}".format(original_dua))
Alangkah lebih baik juga dicantumkan contoh hasil print dalam bentuk komentar :D

2021-11-24 01:59 UTC, AdhyWiranto44 commented on Basic/list_comprehension.py
> +print("Original Range : {}".format(original_dua))
@KelvinMulyawan

2021-11-29 10:58 UTC, merged