feat: menambahkan algoritma terbaru
bellshade/Python pull request #189
Opened 2021-12-22 03:47 UTC by IlhamriSKY

# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [ ] pytest
- [x] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``windows``
- ``python`` = ``python3.x``

linked issue #NOMOR_ISSUE

2021-12-24 02:41 UTC, slowy07 commented
masukkan mobile yang diperlukan ke dalam ``requirements.txt`` dan kemudian testing kembali dengan cara commit

2021-12-24 02:42 UTC, slowy07 commented
kemudian jalankan format kode dengan menggunakan modul ``black`` dengan perintah

```bash
black namafile.py
```
atau secara sekaligus
```bash
black .
```
atau degan jenis versi tertentu dari python
```
python3 -m black .
```

2021-12-24 03:48 UTC, athallahmaajid requested changes
mostly udah bagus, tapi sql nya bisa dirapihin tuh kak
oh ya, ada beberapa typo seperti `costume` yang seharusnya `custom`
saya harap dapat diperbaiki ya kak :pray:

2021-12-24 13:25 UTC, athallahmaajid requested changes
tanda kutip di sql nya salah mas, seharusnya pake `'` dan bukan `

2021-12-25 05:42 UTC, IlhamriSKY commented
Python testing Failing no modul flask, padahal sudah saya masukan ke requirements.txt

2022-01-07 07:57 UTC, IlhamriSKY commented
Adakah update untuk ini?

2022-01-14 01:08 UTC, slowy07 commented
@athallahmaajid

2022-01-14 08:52 UTC, athallahmaajid requested changes

2022-03-30 03:30 UTC, IlhamriSKY commented
Apakah ada perkembangan atau catatan untuk PR ini?

2022-07-11 05:26 UTC, closed without merging

2022-07-26 09:01 UTC, norinorin reviewed
Ada beberapa penamaan rute yang menurut saya perlu diganti. Coba untuk tidak kasih kata kerja di rute, cukup metode HTTP yang menyiratkan kata kerjanya.

2022-07-26 09:01 UTC, norinorin commented on web_programming/flask_api/contoh/main.py
> +                edit("name", name, user_id)
Query 3 kali? Bisa dipastikan ga ada overhead?