feat: menambahkan algoritma incremental_root_search
bellshade/Python pull request #192
Opened 2021-12-25 05:18 UTC by lymau

# Deskripsi (Description)
menambahkan algoritma baru pada materi analisis numerik yaitu incremental root search. Incremental root search adalah algoritma untuk mencari nilai akar pada sebuah persamaan non linear satu variabel jika diberikan interval.

# Checklist:
##### Umum:
- [x] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [x] pytest
- [x] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``EndeavourOS``
- ``python`` = ``python 3.8.8``

linked issue #NOMOR_ISSUE

2021-12-25 23:40 UTC, slowy07 requested changes

2021-12-25 23:40 UTC, slowy07 commented on algorithm/arithmetic_analysis/rootsearch.py
> +            area di bawah kurva persamaan f.
disaarankan menggunakan komentar (``#``) jik tidak memiliki docstring test

2021-12-25 23:40 UTC, slowy07 commented on algorithm/arithmetic_analysis/rootsearch.py
> +    f(x) = x^3 - 10x^2 + 5
disaarankan menggunakan komentar (``#``) jik tidak memiliki docstring test

2021-12-27 02:53 UTC, lymau commented on algorithm/arithmetic_analysis/rootsearch.py
> +    f(x) = x^3 - 10x^2 + 5
oke, sudah.

2021-12-27 05:30 UTC, slowy07 approved these changes
LGTM, terima kasih atas kontribusinya @lymau 
untuk commit check diperhatikan kembali, dan bisa dilihat penggunaanya pada ``CONTRIBUTING.md``
![pr_401](https://user-images.githubusercontent.com/40540262/147437714-9724f3a8-c4c2-4889-a4c4-9c05b2ebfe75.png)

2021-12-27 05:31 UTC, merged