fix: Memperbaiki dokumentasi
bellshade/Python pull request #199
Opened 2022-08-26 15:01 UTC by deovaliandro

# Deskripsi (Description)
1. Memperbaiki dan merapikan penulisan,
2. Mengubah beberapa penjelasan.

# Checklist:
##### Umum:
- [ ] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [x] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [x] pytest
- [ ] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux``
- ``python`` = ``Python 3.10``

2022-08-27 23:05 UTC, slowy07 requested changes
docstring digunakan sebagai dokumentasi testing file, untuk sebagai berikut diusahakan menggunakan fungsi komentar tanda pagar ``#``, bisakah kamu mengganti beberapa fungsi komentar yang diubah dari docstring menjadi komentar ``#`` ??

2022-08-27 23:05 UTC, slowy07 commented on Basic/04_operator/operator_perbandingan.py
> +"""
docstring digunakan sebagai dokumentasi testing file, untuk sebagai berikut diusahakan menggunakan fungsi komentar tanda pagar ``#``

2022-08-27 23:05 UTC, slowy07 commented on Basic/04_operator/operator_penugasan.py
> +menetapkan nilai suatu variable
docstring digunakan sebagai dokumentasi testing file, untuk sebagai berikut diusahakan menggunakan fungsi komentar tanda pagar ``#``

2022-08-27 23:05 UTC, slowy07 commented on Basic/04_operator/operator_aritmatika.py
> +"""
docstring digunakan sebagai dokumentasi testing file, untuk sebagai berikut diusahakan menggunakan fungsi komentar tanda pagar ``#``

2022-08-27 23:05 UTC, slowy07 commented on Basic/02_tipe_data/tipe_data.py
> +"""
docstring digunakan sebagai dokumentasi testing file, untuk sebagai berikut diusahakan menggunakan fungsi komentar tanda pagar ``#``

2022-08-28 10:28 UTC, deovaliandro commented
@slowy07 terima kasih, saya akan memperbaikinya 👍🏼 .

2022-08-28 10:37 UTC, deovaliandro commented
> @slowy07 terima kasih, saya akan memperbaikinya 👍🏼 .

[Perubahan sudah dilakukan](https://github.com/bellshade/Python/pull/199/commits/9b1dc96179d47d8d2e5404ba3d6fa1b3c18772c8).

2022-08-28 16:54 UTC, slowy07 approved these changes
LGTM, terima kasih atas kontribusinya @deovaliandro

2022-08-29 10:56 UTC, merged