docs: Merevisi README materi ke 4
bellshade/Python pull request #209
Opened 2022-10-05 18:42 UTC by manabil

## Deskripsi (Description)

- Menambahkan keterangan 
- Memperbaiki tabel

## Checklist:
### Umum:

- [ ] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [x] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:

 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [ ] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

### Unit Testing dan Linting:

- [ ] pytest
- [x] flake8

## Environment

Saya menggunakan (I'm using):

- ``os`` = ``windows``
- ``python`` = ``python 3.9.7``

2022-10-05 23:02 UTC, slowy07 requested changes
butuh beberapa perubahan untuk penggunaan string pada python

2022-10-05 23:02 UTC, slowy07 commented on Basic/02_tipe_data/tipe_data.py
> +teks_string_2 = 'halo dunia!'
string pada python disarankan menggunakan double quote
```suggestion
teks_string_2 = "halo dunia!"
```

2022-10-05 23:02 UTC, slowy07 commented on Basic/03_variable/string_variable.py
> +pesan = 'saya pergi ke pasar'
string pada python disarankan menggunakan double quote
```suggestion
pesan = "saya pergi ke pasar"
```

2022-10-06 17:47 UTC, manabil reviewed
ok kak terimakasih atas sarannya , sudah saya ganti kembali ke single quote

2022-10-08 10:18 UTC, slowy07 approved these changes
LGTM, terima kasih atas kontribusinya @manabil

2022-10-08 10:18 UTC, merged