add: Operator
bellshade/Python pull request #27
Opened 2021-09-15 08:27 UTC by athallahmaajid

# Deskripsi (Description)

# Checklist:
##### Umum:
- [ ] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [ ] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [] pytest
- [x] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``
- ``python`` = ``python3 -V (unix) / py -3 -V (Windows-Python launcher)``

# Maintainer
**Python Maintainer**:
@norinorin
@athallahmaajid
@KelvinMulyawan
@slowy07

**Docs maintainer**:
@dydrmr5
@nomadkode

2021-09-15 08:55 UTC, slowy07 requested changes
coba tambahin supress comment biar lewat LGTM

2021-09-15 08:55 UTC, slowy07 commented on Basic/Operator.py
> +print("a is a:", a is a)
tambahin ini biar supress di lgtmnya jadi biar kagak warning
```suggestion
print("a is a:", a is a) # lgtm [py/comparison-of-identical-expressions]
```

2021-09-15 09:39 UTC, slowy07 approved these changes

2021-09-15 09:39 UTC, merged

2021-09-16 12:16 UTC, nomadkode commented
nice