Menambahkan Algoritma pengklasifikasi Hutan Acak #271
bellshade/Python pull request #272
Opened 2023-06-05 11:04 UTC by ShubhamZoro

## Deskripsi (Description)

## Checklist:
### Umum:

- [ ] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:

 - [ ] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [ ] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [ ] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

### Unit Testing dan Linting:

- [ ] pytest
- [ ] flake8

## Environment

Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``
- ``python`` = ``python3 -V (unix) / py -3 -V (Windows-Python launcher)``

linked issue #NOMOR_ISSUE

2023-06-05 13:44 UTC, slowy07 requested changes
i think that's problem from linting check (``flake8``), can you fix that by format and follow the guideline from ``CONTIRBUTING.md``, thanks !

2023-06-05 13:44 UTC, slowy07 commented on implementation/artificial_intelligence/random_forest.py
> +        """
line too long, must be < 100 char

2023-06-05 13:44 UTC, slowy07 commented on implementation/artificial_intelligence/random_forest.py
> +# Itu diinisialisasi dengan parameter max_depth (kedalaman maksimum pohon) dan min_samples_leaf (jumlah minimum sampel yang diperlukan untuk membuat simpul daun).#
line too long, must be < 100 char

2023-06-05 13:44 UTC, slowy07 commented on implementation/artificial_intelligence/random_forest.py
> +    # Fungsi build_tree secara rekursif membagi data berdasarkan fitur dan nilai terbaik, dengan mempertimbangkan perolehan informasi
line too long, must be < 100 char

2023-06-05 13:44 UTC, slowy07 commented on implementation/artificial_intelligence/random_forest.py
> +# Itu diinisialisasi dengan parameter num_trees (jumlah pohon di hutan), max_depth (kedalaman maksimum setiap pohon), dan min_samples_leaf (jumlah minimum sampel yang diperlukan untuk membuat simpul
line too long, must be < 100 char

2023-06-05 14:26 UTC, ShubhamZoro commented on implementation/artificial_intelligence/random_forest.py
> +    # Metode prediksi membuat prediksi untuk satu set sampel input dengan menggabungkan prediksi dari setiap pohon dan mengambil suara mayoritas.
Thanks for the guidance.

2023-06-05 16:52 UTC, ShubhamZoro commented
Please review it.

2023-06-06 12:25 UTC, slowy07 approved these changes
LGTM, thanks for contribution @ShubhamZoro !

linked issue #246

2023-06-06 12:26 UTC, merged

2023-06-06 12:42 UTC, ShubhamZoro commented
LGTM I will look into this issue as well.