feat: menambahkan algoritm counter(yaudah)
bellshade/Python pull request #273
Opened 2023-06-08 15:19 UTC by kayabaakihiko13

## Deskripsi (Description)

## Checklist:
### Umum:

- [x] Saya menambah algoritma terbaru.
- [] Saya memperbaiki algoritma yang sudah ada.
- [] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:

 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

### Unit Testing dan Linting:

- [x] pytest
- [x] flake8

## Environment

Saya menggunakan (I'm using):

- ``os`` = ``linux``
- ``python`` = ``python3 -V (unix) ``

linked issue #NOMOR_ISSUE

2023-06-08 17:40 UTC, slowy07 requested changes
LGTM, kode diatas terlihat sudah bagus, tapi kurangnya typehinting, jadi untuk kode tersebut mudah dibaca dan mengikuti peraturan dari ``CONTRIBUTING.md``

kamu juga bisa menggunakan fungsi ``super().__init__()`` dalam konstruktor kelas dari ``counter`` dengan ini sebagai contoh

```python
class Counter(dict):
    def __init__(self, iterable: Optional[Dict[Any, int]] = None, **kwargs: int) -> None:
        super().__init__()
        self.update(iterable, **kwarg
````
tujuannya antara lain untuk memastikan inisialisassi tepat dari kelas ``Counter`` yang bertipe ``dict``

2023-06-08 17:40 UTC, slowy07 commented on math/counter.py
> +    def __init__(self, iterables=None, **kwargs):
```suggestion
    def __init__(self, iterable: Optional[Dict[Any, int]] = None, **kwargs: int) -> None:
```
formatting kodenya agar tidak tercatch dengan ``flake8``

2023-06-08 17:40 UTC, slowy07 commented on math/counter.py
> +            self.update(kwargs)
```suggestion
        if iterable is not None:
            if hasattr(iterable, "items"):
                if self:
                    self_get = self.get
                    for element, count in iterable.items():
                        self[element] = self_get(element, 0) + count
                else:
                    dict.update(self, iterable)
            else:
                self_get = self.get
                for element in iterables:
                    self[element] = self_get(element, 0) + 1
        if kwargs:
            self.update(kwargs)
```

2023-06-08 17:40 UTC, slowy07 commented on math/counter.py
> +    def paling_muncul(self, n=None):
```suggestion
    def paling_muncul(self, n: Optional[int] = None) -> List[Tuple[Any, int]]:
```

2023-06-08 18:30 UTC, kayabaakihiko13 commented
> LGTM, kode diatas terlihat sudah bagus, tapi kurangnya typehinting, jadi untuk kode tersebut mudah dibaca dan mengikuti peraturan dari ``CONTRIBUTING.md``
> 
> kamu juga bisa menggunakan fungsi ``super().__init__()`` dalam konstruktor kelas dari ``counter`` dengan ini sebagai contoh
> 
> ```python
> class Counter(dict):
>     def __init__(self, iterable: Optional[Dict[Any, int]] = None, **kwargs: int) -> None:
>         super().__init__()
>         self.update(iterable, **kwarg
> ````
> tujuannya antara lain untuk memastikan inisialisassi tepat dari kelas ``Counter`` yang bertipe ``dict``

Berati di bagian dict pada class Counter(dict) tidak di perlukan kak?

2023-06-08 19:03 UTC, slowy07 commented
> ```python
>     def __init__(self, iterable: Optional[Dict[Any, int]] = None, **kwargs: int) -> None:
> ```

sebenarnya boleh menggunakan kode diatas atau menggunakan contoh yang disarankan, keduanya memberikan informasi yang baik contoh yang diberikan bisa dijadikan acuan untuk improvisasi

2023-06-09 17:33 UTC, slowy07 approved these changes
LGTM, terima kasih atas kontribusinya @kayabaakihiko13 !

2023-06-09 17:35 UTC, merged