feat: update algoritma ridge regession
bellshade/Python pull request #282
Opened 2023-06-21 17:34 UTC by kayabaakihiko13

## Deskripsi (Description)

## Checklist:
### Umum:

- [ ] Saya menambah algoritma terbaru.
- [x] Saya memperbaiki algoritma yang sudah ada.
- [x] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:

 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

### Unit Testing dan Linting:

- [x] pytest
- [x] flake8

## Environment

Saya menggunakan (I'm using):

- ``os`` = ``linux``
- ``python`` = ``python3 -V (unix)``

linked issue #NOMOR_ISSUE

2023-06-21 23:16 UTC, slowy07 requested changes

2023-06-21 23:16 UTC, slowy07 commented on implementation/artificial_intelligence/rigde_regession.py
> +):
```suggestion
def costfunction(
    x_data: np.ndarray,
    y_data: np.ndarray,
    alpha: float,
    weigth: np.ndarray,
    panjang_data: int,
) -> float:
```

2023-06-21 23:16 UTC, slowy07 commented on implementation/artificial_intelligence/rigde_regession.py
> +):
```suggestion
def step_gradient_descent(
    data_x: np.ndarray,
    data_y: np.ndarray,
    alpha: float,
    weight: np.ndarray,
    panjang_data: int,
) -> np.ndarray:
```

2023-06-21 23:16 UTC, slowy07 commented on implementation/artificial_intelligence/rigde_regession.py
>      def fit(self, x: np.array, y: np.array):
```suggestion
    def fit(self, x: np.ndarray, y: np.ndarray) -> np.ndarray:
```

2023-06-21 23:16 UTC, slowy07 commented on implementation/artificial_intelligence/rigde_regession.py
>      def transform(self, x: np.array):
```suggestion
    def transform(self, x: np.ndarray) -> np.ndarray:
```

2023-06-21 23:16 UTC, slowy07 commented on implementation/artificial_intelligence/rigde_regession.py
>      def error_value(self, x: np.array, y: np.array):
```suggestion
    def error_value(self, x: np.ndarray, y: np.ndarray) -> np.ndarray:
```

2023-06-22 05:00 UTC, kayabaakihiko13 commented on implementation/artificial_intelligence/rigde_regession.py
> +):
> 

untuk algoritmnya apa udah sesuai atau masih ada kesalahan kak @slowy07 ?
soalnya yang aku tahu ini dia sama kayak linear regession biasa kak

2023-06-22 06:19 UTC, kayabaakihiko13 commented on implementation/artificial_intelligence/rigde_regession.py
>      def error_value(self, x: np.array, y: np.array):
> 

maksud dari line 59 ke 96,97,98 itu apa kak @slowy07 ?

2023-06-24 12:32 UTC, slowy07 approved these changes
LGTM, terima kasih atas kontribusinya @kayabaakihiko13 !

2023-06-24 12:32 UTC, merged