add: menambahkan algoritma bubblesort
bellshade/Python pull request #29
Opened 2021-09-21 16:47 UTC by ibrahim4529

# Deskripsi (Description)
Menambahkan algoritma bubblesort
Terimakasih

# Checklist:
##### Umum:
- [X] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [X] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [X] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [X] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [X] pytest
- [X] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``macOS``
- ``python`` = ``Python 3.7.6``

linked issue #NOMOR_ISSUE

2021-09-21 23:54 UTC, slowy07 reviewed
LGTM, tinggal tambahkan yang dibutuhkan saja,terma kasih!!

2021-09-21 23:54 UTC, slowy07 commented on sorting/bubblesort.py
> +
LGTM, tinggal tambahkan aja
```suggestion
from __future__ import annotations
```

https://mypy.readthedocs.io/en/latest/runtime_troubles.html

2021-09-22 00:49 UTC, slowy07 approved these changes
LGTM, request squash merge @bellshade/python-team

2021-09-22 04:19 UTC, norinorin requested changes
Mungkin bisa menggunakan snake_case mas, biar konsisten. Juga kelihatannya implementasinya masih belum sempurna:
```
>>> bubbleSort([5, 2, 1, 3, 2, 5, 7, 3, 4])
[1, 5, 2, 7, 3, 3, 5, 4, 2]  # expected [1, 2, 2, 3, 3, 4, 5, 5, 7]
```

2021-09-22 04:59 UTC, norinorin commented
Sidenote: seperti yang sudah disebutkan di [CONTRIBUTING.md](https://github.com/bellshade/Python/blob/main/CONTRIBUTING.md), kedepannya buat issue dulu ya. Biar ga double-work, karena di local branch sudah ada implementasi bubble sort. Tp gapapa, lanjut aja kerjain requested changes-nya. Nanti kalo sudah OK, kita merge 👍

2021-09-22 05:19 UTC, ibrahim4529 commented
> Sidenote: seperti yang sudah disebutkan di [CONTRIBUTING.md](https://github.com/bellshade/Python/blob/main/CONTRIBUTING.md), kedepannya buat issue dulu ya. Biar ga double-work, karena di local branch sudah ada implementasi bubble sort. Tp gapapa, lanjut aja kerjain requested changes-nya. Nanti kalo sudah OK, kita merge 👍

ok mas Terimakasih my wrong ga baca dengan teliti 🙏

2021-09-22 05:30 UTC, norinorin requested changes

2021-09-22 05:30 UTC, norinorin commented on sorting/bubblesort.py
> +from __future__ import annotations
```suggestion

```

2021-09-22 05:30 UTC, norinorin commented on sorting/bubblesort.py
> +from __future__ import annotations
Ini ga ngasih efek apa apa di kasus ini.

2021-09-22 05:30 UTC, norinorin commented on sorting/bubblesort.py
> +                numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]
Diambil dari [CONTRIBUTING](https://github.com/bellshade/Python/blob/main/CONTRIBUTING.md):
>>> - hasil pekerjaan kamu adalah buatan kamu sendiri dan tidak ada hak cipta dari orang lain
    - jika kami menemukan kesamaan maka kami tidak `merged`.

2021-09-22 05:30 UTC, norinorin commented on sorting/bubblesort.py
> +    testing()
```suggestion
    # testing()
```

2021-09-23 12:00 UTC, norinorin commented on sorting/bubblesort.py
> +                numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]
Ada niat untuk ubah approach-nya? Karena sangat identik dengan yg ada di [GFG](https://www.geeksforgeeks.org/bubble-sort/). Juga, tambah komen penjelasannya mas. Idealnya, tiap line bisa dikasih komen.

2021-09-23 23:37 UTC, norinorin commented on sorting/bubblesort.py
> +                numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]
Identical to one of the [GFG examples](https://www.geeksforgeeks.org/python-program-for-bubble-sort/). We do appreciate your PR, but we're closing this as you've proposed 2 implementations and both seemed to be taken from GFG. Feel free to reopen with another implementation. Thanks!

2021-09-23 23:38 UTC, closed without merging