add: tipe_data python
bellshade/Python pull request #31
Opened 2021-09-28 02:24 UTC by khairanabila

# Deskripsi (Description)
tipe data yang terdapat pada python

# Checklist:
##### Umum:
- [x] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [ ] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [x] pytest
- [ ] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``macOS``
- ``python`` = ``python3.9``

linked issue #NOMOR_ISSUE

2021-09-28 05:18 UTC, athallahmaajid approved these changes

2021-09-28 08:02 UTC, norinorin requested changes
Hai, terima kasih untuk PR-nya. Mohon cek review di bawah :)

2021-09-28 08:02 UTC, norinorin commented on Basic/tipe_data/tipe_data.py
> +print(nama_siswa)
Ini ga print type-nya seperti sebelumnya?

2021-09-28 08:02 UTC, norinorin commented on Basic/tipe_data/tipe_data.py
> +# tipe data majemuk yaitu list, tuple, range
Mungkin bisa dijelaskan juga perbedaan dari tipe-tipe datanya. Misalnya bisa disebutkan apakah tipe data ini mutable, dapat memiliki elemen duplikat, dan sebagainya.

2021-09-28 11:28 UTC, norinorin commented
Link #33

2021-09-29 03:24 UTC, slowy07 approved these changes
@bellshade/python-team

2021-09-29 07:25 UTC, norinorin requested changes
Sorry kelewat 😅

2021-09-29 07:25 UTC, norinorin commented on Basic/tipe_data/tipe_data.py
> +# hasul dari kedua value
```suggestion
# hasil dari kedua value
```

2021-09-29 07:25 UTC, norinorin commented on Basic/tipe_data/tipe_data.py
> +# suatu tipe data yang terdapat pada variabel
Ini maksudnya `penggunaan type() sebagai pemeriksa tipe data dari suatu variabel`?

2021-09-29 07:25 UTC, norinorin commented on Basic/tipe_data/tipe_data.py
> +# tipe data majemuk yaitu list, tuple, set dan range
```suggestion
# tipe data majemuk yaitu list, tuple, set, dan range
```

2021-09-29 07:25 UTC, norinorin commented on Basic/tipe_data/tipe_data.py
> +# tipe data majemuk yaitu list, tuple, set dan range
Pakai oxford comma agar konsisten dengan line sebelumnya.

2021-09-29 07:51 UTC, khairanabila commented on Basic/tipe_data/tipe_data.py
> +# suatu tipe data yang terdapat pada variabel
iyaa @norinorin

2021-09-29 13:43 UTC, norinorin approved these changes

2021-09-29 15:54 UTC, merged