feat: Menambahkan materi baru pada object_oriented_programming/advance
bellshade/Python pull request #313
Opened 2024-03-07 07:44 UTC by tomsdroid

## Deskripsi (Description)

## Checklist:
### Umum:

- [ ] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:

 - [ ] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [ ] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [ ] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

### Unit Testing dan Linting:

- [ ] pytest
- [ ] flake8

## Environment

Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``
- ``python`` = ``python3 -V (unix) / py -3 -V (Windows-Python launcher)``

linked issue #NOMOR_ISSUE

2024-03-07 08:45 UTC, kayabaakihiko13 commented on object_oriented/advance/pycode/decorators/contoh_decorators2.py
> +def kasar(s):
kasih hype typing biar jelas yang baca kak 

```py
def kasar(s:str)->str:
```

2024-03-07 08:51 UTC, kayabaakihiko13 commented on object_oriented/advance/pycode/decorators/contoh_decorators3.py
> +def users(nama):
```py
from typing import Callable
def users(nama:str)->Callable:
```

2024-03-07 08:51 UTC, kayabaakihiko13 commented on object_oriented/advance/pycode/decorators/contoh_decorators3.py
> +    def belajar(s):
```py
def belajar(s:str)-> str:
```

2024-03-07 11:28 UTC, slowy07 requested changes
perbaiki panjang dari koemntar kode, gunakanlah docstring, kemudian gunakan fungsi ``if __name__ == "__main__":``

2024-03-07 11:28 UTC, slowy07 commented on object_oriented/advance/pycode/decorators/decorators.py
> +wpu()
```suggestion
if __name__ == "__main__":
	wpu()
```

2024-03-07 11:28 UTC, slowy07 commented on object_oriented/advance/pycode/decorators/decorators_chaining.py
> +print(num2())
hindari penggunaan print, gunakan docstring

2024-03-07 11:28 UTC, slowy07 commented on object_oriented/advance/pycode/magic_methods/main.py
> +del user2
```suggestion
if __name__ == "__main__":
	# Membuat object user1 dari Class Pastikom
	user1 = Pastikom("Bellshade", "Bellshade@Pastikom")
	# Membuat object user1 dari Class Pastikom
	user2 = Pastikom("TomsDroid", "tomsdroid@Pastikom")


	# Menampilkan value object user1 dari Class Pastikom
	print(user1)
	# Menghapus value object user1 dari Class Pastikom
	del user2
```

2024-03-07 11:28 UTC, slowy07 commented on object_oriented/advance/pycode/generators/generators_while.py
> +        time.sleep(0.5)
hindari pengunaan dari fungsi daripada ``time.sleep()``

2024-03-07 11:28 UTC, slowy07 commented on object_oriented/advance/pycode/decorators/contoh_decorators3.py
> +print(s1("Fullstack"))
```suggestion
if __name__ == "__main__":
	# Buatlah objek sesuai keinginan, dan berikan nilai fungsi (users) didalam objek.
	s1 = users("bellshade")

	# Cetak objek yang sudah di definisikan, yang di ikuti dengan tanda kurung ().
	print(s1("Fullstack"))
```

2024-03-07 11:28 UTC, slowy07 commented on object_oriented/advance/README.md
reformat kodenya dengan menggunakan markdown beautify

2024-03-21 11:16 UTC, slowy07 approved these changes

2024-04-05 06:48 UTC, athallahmaajid approved these changes

2024-04-06 12:14 UTC, merged