Task/loop
bellshade/Python pull request #38
Opened 2021-09-28 15:34 UTC by KelvinMulyawan

# Deskripsi (Description)

# Checklist:
##### Umum:
- [ x] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [ x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [ ] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [ x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [ x] pytest
- [ ] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``windows``
- ``python`` = ``py 3.9``

linked issue #NOMOR_ISSUE

2021-09-28 16:12 UTC, slowy07 requested changes
https://app.codacy.com/gh/bellshade/Python/pullRequest?prid=8157291

@bellshade/python-team

2021-10-01 07:13 UTC, athallahmaajid requested changes
```python
for item in angka:
    print(item)
    break
else:
    print("Selesai !")
```
else in this code is unreachable cause the `angka` is always have members,
you can create a new variable like
```python
kosong = []

for i in kosong:
    print(item)
    break
else:
    print("kosong!")
```

2021-10-01 07:39 UTC, slowy07 requested changes
file [for_loop.py](https://github.com/bellshade/Python/blob/eda5f79983fa851e927847d18fc088dc25faec99/Basic/looping/for_loop.py) tinggal di reformat aj pakai black

2021-10-05 03:45 UTC, dydrmr5 approved these changes

2021-10-05 03:53 UTC, norinorin commented
@dydrmr5 Yakin ga ada yang mau dirapihin?

2021-10-05 03:59 UTC, dydrmr5 commented
> @dydrmr5 Yakin ga ada yang mau dirapihin?

my bad. dia belum menuhin request changes nya ya? lg gajelas saya. sorry

2021-10-05 04:03 UTC, norinorin commented
> > @dydrmr5 Yakin ga ada yang mau dirapihin?
> 
> my bad. dia belum menuhin request changes nya ya? lg gajelas saya. sorry

Engga kok, requested changes-nya lebih ke kodenya. Dari mas sendiri gaada yang mau dirapihin untuk dokumentasi penjelasannya? Misalnya tanda baca, tata bahasa, dsb?

2021-10-05 04:12 UTC, dydrmr5 commented
> > > @dydrmr5 Yakin ga ada yang mau dirapihin?
> > 
> > 
> > my bad. dia belum menuhin request changes nya ya? lg gajelas saya. sorry
> 
> Engga kok, requested changes-nya lebih ke kodenya. Dari mas sendiri gaada yang mau dirapihin untuk dokumentasi penjelasannya? Misalnya tanda baca, tata bahasa, dsb?

ada2. jd td yg salah lihat changes di commit terakhir ternyata. ga sadar 😄 .

2021-10-05 04:37 UTC, dydrmr5 commented on Basic/looping/README.md
> +
typo : `instrusi`. harusnya `instruksi`
akan lebih baik jika kalimatnya begini, "Looping adalah urutan instruksi yang akan dijalankan, apabila suatu kondisi terpenuhi.

2021-10-05 04:37 UTC, dydrmr5 commented on Basic/looping/README.md
> +
dalam penjelasan, akan lebih baik jika nama variable diapit dengan tanda backtick agar tertulis jadi : variable `a`.
Penjelasannya dipersingkat saja, jgn terlalu boros bahasa. "Penjelasan: apabila variable `a` yang awalnya 1, dan seterusnya..

2021-10-06 14:12 UTC, closed without merging