Operator perbandingan
bellshade/Python pull request #40
Opened 2021-10-01 10:54 UTC by athallahmaajid

# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [x] black
- [x] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux``
- ``python`` = ``python 3.8.10``

2021-10-01 12:12 UTC, norinorin requested changes
Ini kenapa String.py nyangkut di sini? Out of scope, kan?

2021-10-01 12:14 UTC, norinorin commented
Oh ya, markdownnya ga sekalian?

2021-10-01 12:28 UTC, norinorin reviewed
Mungkin bisa kasih *expected output*-nya kayak gini?

2021-10-01 12:28 UTC, norinorin commented on Basic/operator/operator_perbandingan.py
> +print("a == b:", a == b)
```suggestion
print("a == b:", a == b)  # False
```

2021-10-01 12:28 UTC, norinorin commented on Basic/operator/operator_perbandingan.py
> +print("a != b:", a != b)
```suggestion
print("a != b:", a != b)  # True
```

2021-10-01 12:28 UTC, norinorin commented on Basic/operator/operator_perbandingan.py
> +print("a > b:", a > b)
```suggestion
print("a > b:", a > b)  # True
```

2021-10-01 12:28 UTC, norinorin commented on Basic/operator/operator_perbandingan.py
> +print("a < b:", a < b)
```suggestion
print("a < b:", a < b)  # False
```

2021-10-01 12:28 UTC, norinorin commented on Basic/operator/operator_perbandingan.py
> +print("a >= b:", a >= b)
```suggestion
print("a >= b:", a >= b)  # True
```

2021-10-01 12:28 UTC, norinorin commented on Basic/operator/operator_perbandingan.py
> +print("a <= b:", a <= b)
```suggestion
print("a <= b:", a <= b)  # False
```

2021-10-01 14:09 UTC, athallahmaajid commented on Basic/operator/operator_perbandingan.py
> +print("a <= b:", a <= b)
nah, pas saya bikin begini kena flake8 om
gimana cara ngilanginnya?

2021-10-01 15:30 UTC, slowy07 approved these changes
LGTM, request @bellshade/python-team

2021-10-02 09:07 UTC, norinorin requested changes

2021-10-02 09:07 UTC, norinorin commented on Basic/operator/README.md
> +- [operator komparasi] (operator_perbandingan.py)
```suggestion
- [operator komparasi](operator_perbandingan.py)
```

2021-10-02 09:07 UTC, norinorin commented on Basic/operator/README.md
> +operasi perbandingan adalah operasi yang digunakan untuk menetapkan suatu bilangan ke dalam variabel
Ini definisi operasi penugasan?

2021-10-02 10:27 UTC, athallahmaajid commented on Basic/operator/README.md
> +operasi perbandingan adalah operasi yang digunakan untuk menetapkan suatu bilangan ke dalam variabel
maap, malem-malem jadi error kepala

2021-10-02 11:06 UTC, norinorin approved these changes

2021-10-02 11:06 UTC, norinorin commented on Basic/operator/README.md
> +print(2 < 3) # True
```suggestion
print(2 < 3)  # False
```

2021-10-02 11:06 UTC, norinorin commented on Basic/operator/README.md
> +print(2 < 3) # True
Last one.

2021-10-02 11:43 UTC, athallahmaajid commented
tinggal merge kan?

2021-10-02 11:43 UTC, slowy07 approved these changes
request @bellshade/python-team

2021-10-02 12:06 UTC, merged