Operator logika
bellshade/Python pull request #43
Opened 2021-10-02 12:57 UTC by athallahmaajid

# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [x] black
- [x] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux``
- ``python`` = ``python 3.8.10``

Issue #32

2021-10-02 13:08 UTC, norinorin requested changes

2021-10-02 13:08 UTC, norinorin commented on Basic/operator/README.md
> +|     not       | Membalikkan hasil, mengembalikan False jika hasilnya True             |
Ini agak kurang tepat sih.

`and` -> mengembalikan nilai *falsy* yang pertama ditemukan. Misalnya: `1 and 0` dan `0 and 1` keduanya bakal ngembaliin 0. `None and 1` bakal ngembaliin `None`. Kalau gaada nilai yang *falsy*, maka operan paling kanan yang dikembaliin, misalnya: `1 and 2` bakal ngembaliin 2.

`or` -> mengembalikan nilai *truthy* pertama yang ditemukan. Misalnya: `1 or 2` bakal return 1. `0 or 2` bakal return 2.

`not` -> mengembalikan `True` jika nilainya *falsy* atau sebaliknya, mengembalikan `False` jika nilainya *truthy*.

2021-10-02 13:08 UTC, norinorin commented on Basic/operator/operator_logika.py
> +print(not(x > 10))  # True
```suggestion
print(not x < 6)  # False
print(not x > 10)  # True
```

2021-10-02 13:08 UTC, norinorin commented on Basic/operator/operator_logika.py
> +print(not(x > 10))  # True
Biar ga disalah artikan sebagai fungsi aja sih.

2021-10-02 13:20 UTC, athallahmaajid commented on Basic/operator/operator_logika.py
> +print(not(x > 10))  # True
oh oke bentar

2021-10-03 01:30 UTC, slowy07 requested changes

2021-10-03 01:30 UTC, slowy07 commented on .pylintrc
> +
ignore folder basic aj untuk codefactor

2021-10-03 11:45 UTC, athallahmaajid commented on .pylintrc
> +
gimana om? saya bikin
```python
ignore=Basic
```
ga bisa

2021-10-03 14:59 UTC, norinorin commented on .pylintrc
> +                       Exception
Out of scope IMHO. Next time buat PR terpisah untuk hal yg di luar lingkup topik PR.

2021-10-04 02:44 UTC, athallahmaajid commented
jadi gimana dah ini ilangin codefactor issue
apa di merge aja?

2021-10-04 02:48 UTC, norinorin commented
Coba jid assign dulu ke variabel, baru print pake not.

2021-10-04 03:05 UTC, norinorin approved these changes

2021-10-04 03:14 UTC, nomadkode approved these changes
Docs safe to LGTM 🚀

2021-10-04 03:24 UTC, merged